# Dockerfile
FROM python:3.11-bookworm

MAINTAINER Mack Hendricks <mack@dsiprouter.org>

COPY ./  /opt/dsiprouter/
WORKDIR /opt/dsiprouter
RUN apt-get update && apt-get install -y build-essential pkg-config python3-pip \
        python3-dev libpq-dev python3-venv libev-dev libffi-dev libmariadb-dev \
        curl python3 firewalld sudo logrotate rsyslog perl sngrep uuid-runtime \
        libsasl2-dev python-dev-is-python3 libldap2-dev libssl-dev

RUN pip install -r ./gui/requirements.txt
ENV DBSERVER ''
ENV DBPORT '3306'
ENV DBUSER ''
ENV DBPASS ''
ENV DBNAME ''

EXPOSE 5000:5000

CMD ["python", "./gui/dsiprouter.py", "runserver"]
