#
# Usrloc module Makefile
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=dsiprouter.so
LIBS=-lssl -lcrypto

SERLIBPATH=../../lib
SER_LIBS+=$(SERLIBPATH)/srutils/srutils
include ../../Makefile.modules
