-- constant values must be added when pre-processing the file (by calling script)
-- using user-defined variables allows us to keep syntax highlighting in our IDEs, but note they won't work without replacement
-- the following strings are expected to be replaced by the pre-processing script (INCLUDE THE PRECEDING @ SYMBOL!):
-- HASHED_CREDS_ENCODED_MAX_LEN
-- AESCTR_CREDS_ENCODED_MAX_LEN

-- DB representation of settings.py with non-db backed settings left out
DROP TABLE IF EXISTS dsip_settings;
/*!40101 SET @saved_cs_client = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE dsip_settings
(
  DSIP_ID                 VARBINARY(@HASHED_CREDS_ENCODED_MAX_LEN) COLLATE 'binary' NOT NULL,
  DSIP_CLUSTER_ID         INT UNSIGNED                                              NOT NULL DEFAULT 1,
  DSIP_CLUSTER_SYNC       TINYINT(1)                                                NOT NULL DEFAULT 1,
  DSIP_PROTO              VARCHAR(16)                                               NOT NULL DEFAULT 'http',
  DSIP_PORT               INT                                                       NOT NULL DEFAULT 5000,
  DSIP_USERNAME           VARCHAR(255)                                              NOT NULL DEFAULT 'admin',
  DSIP_PASSWORD           VARBINARY(@HASHED_CREDS_ENCODED_MAX_LEN) COLLATE 'binary' NOT NULL,
  DSIP_IPC_PASS           VARBINARY(@AESCTR_CREDS_ENCODED_MAX_LEN) COLLATE 'binary' NOT NULL,
  DSIP_API_PROTO          VARCHAR(16)                                               NOT NULL DEFAULT 'http',
  DSIP_API_PORT           INT                                                       NOT NULL DEFAULT 5000,
  DSIP_PRIV_KEY           VARCHAR(255)                                              NOT NULL DEFAULT '/etc/dsiprouter/privkey',
  DSIP_PID_FILE           VARCHAR(255)                                              NOT NULL DEFAULT '/run/dsiprouter/dsiprouter.pid',
  DSIP_UNIX_SOCK          VARCHAR(255)                                              NOT NULL DEFAULT '/run/dsiprouter/dsiprouter.sock',
  DSIP_IPC_SOCK           VARCHAR(255)                                              NOT NULL DEFAULT '/run/dsiprouter/ipc.sock',
  DSIP_API_TOKEN          VARBINARY(@AESCTR_CREDS_ENCODED_MAX_LEN) COLLATE 'binary' NOT NULL,
  DSIP_LOG_LEVEL          INT                                                       NOT NULL DEFAULT 3,
  DSIP_LOG_FACILITY       INT                                                       NOT NULL DEFAULT 18,
  DSIP_SSL_KEY            VARCHAR(255)                                              NOT NULL DEFAULT '',
  DSIP_SSL_CERT           VARCHAR(255)                                              NOT NULL DEFAULT '',
  DSIP_SSL_CA             VARCHAR(255)                                              NOT NULL DEFAULT '/etc/dsiprouter/certs/ca-list.pem',
  DSIP_SSL_EMAIL          VARCHAR(255)                                              NOT NULL DEFAULT '',
  DSIP_CERTS_DIR          VARCHAR(255)                                              NOT NULL DEFAULT '/etc/dsiprouter/certs',
  VERSION                 VARCHAR(32)                                               NOT NULL,
  DEBUG                   TINYINT(1)                                                NOT NULL DEFAULT 0,
  `ROLE`                  VARCHAR(32)                                               NOT NULL DEFAULT '',
  GUI_INACTIVE_TIMEOUT    INT UNSIGNED                                              NOT NULL DEFAULT 20,
  KAM_DB_HOST             VARCHAR(255)                                              NOT NULL DEFAULT 'localhost',
  KAM_DB_DRIVER           VARCHAR(255)                                              NOT NULL DEFAULT '',
  KAM_DB_TYPE             VARCHAR(255)                                              NOT NULL DEFAULT 'mysql',
  KAM_DB_PORT             VARCHAR(255)                                              NOT NULL DEFAULT '3306',
  KAM_DB_NAME             VARCHAR(255)                                              NOT NULL DEFAULT 'kamailio',
  KAM_DB_USER             VARCHAR(255)                                              NOT NULL DEFAULT 'kamailio',
  KAM_DB_PASS             VARBINARY(@AESCTR_CREDS_ENCODED_MAX_LEN) COLLATE 'binary' NOT NULL,
  KAM_KAMCMD_PATH         VARCHAR(255)                                              NOT NULL DEFAULT '/usr/sbin/kamcmd',
  KAM_CFG_PATH            VARCHAR(255)                                              NOT NULL DEFAULT '/etc/kamailio/kamailio.cfg',
  KAM_TLSCFG_PATH         VARCHAR(255)                                              NOT NULL DEFAULT '/etc/kamailio/tls.cfg',
  RTP_CFG_PATH            VARCHAR(255)                                              NOT NULL DEFAULT '/etc/kamailio/kamailio.cfg',
  FLT_CARRIER             INT                                                       NOT NULL DEFAULT 8,
  FLT_PBX                 INT                                                       NOT NULL DEFAULT 9,
  FLT_MSTEAMS             INT                                                       NOT NULL DEFAULT 17,
  FLT_OUTBOUND            INT                                                       NOT NULL DEFAULT 8000,
  FLT_INBOUND             INT                                                       NOT NULL DEFAULT 9000,
  FLT_LCR_MIN             INT                                                       NOT NULL DEFAULT 10000,
  FLT_FWD_MIN             INT                                                       NOT NULL DEFAULT 20000,
  DEFAULT_AUTH_DOMAIN     VARCHAR(255)                                              NOT NULL DEFAULT 'sip.dsiprouter.org',
  TELEBLOCK_GW_ENABLED    TINYINT(1)                                                NOT NULL DEFAULT 0,
  TELEBLOCK_GW_IP         VARCHAR(255)                                              NOT NULL DEFAULT '62.34.24.22',
  TELEBLOCK_GW_PORT       VARCHAR(255)                                              NOT NULL DEFAULT '5066',
  TELEBLOCK_MEDIA_IP      VARCHAR(255)                                              NOT NULL DEFAULT '',
  TELEBLOCK_MEDIA_PORT    VARCHAR(255)                                              NOT NULL DEFAULT '',
  FLOWROUTE_ACCESS_KEY    VARCHAR(255)                                              NOT NULL DEFAULT '',
  FLOWROUTE_SECRET_KEY    VARCHAR(255)                                              NOT NULL DEFAULT '',
  FLOWROUTE_API_ROOT_URL  VARCHAR(255)                                              NOT NULL DEFAULT 'https://api.flowroute.com/v2',
  HOMER_ID                BIGINT                                                    NOT NULL,
  HOMER_HEP_HOST          VARCHAR(255)                                              NOT NULL DEFAULT '',
  HOMER_HEP_PORT          INT                                                       NOT NULL DEFAULT 9060,
  NETWORK_MODE            INT                                                       NOT NULL DEFAULT 0,
  IPV6_ENABLED            TINYINT(1)                                                NOT NULL DEFAULT 0,
  INTERNAL_IP_ADDR        VARCHAR(255)                                              NOT NULL DEFAULT '',
  INTERNAL_IP_NET         VARCHAR(255)                                              NOT NULL DEFAULT '',
  INTERNAL_IP6_ADDR       VARCHAR(255)                                              NOT NULL DEFAULT '',
  INTERNAL_IP6_NET        VARCHAR(255)                                              NOT NULL DEFAULT '',
  INTERNAL_FQDN           VARCHAR(255)                                              NOT NULL DEFAULT '',
  EXTERNAL_IP_ADDR        VARCHAR(255)                                              NOT NULL DEFAULT '',
  EXTERNAL_IP6_ADDR       VARCHAR(255)                                              NOT NULL DEFAULT '',
  EXTERNAL_FQDN           VARCHAR(255)                                              NOT NULL DEFAULT '',
  PUBLIC_IFACE            VARCHAR(255)                                              NOT NULL DEFAULT '',
  PRIVATE_IFACE           VARCHAR(255)                                              NOT NULL DEFAULT '',
  UPLOAD_FOLDER           VARCHAR(255)                                              NOT NULL DEFAULT '/tmp',
  MAIL_SERVER             VARCHAR(255)                                              NOT NULL DEFAULT 'smtp.gmail.com',
  MAIL_PORT               INT                                                       NOT NULL DEFAULT 587,
  MAIL_USE_TLS            TINYINT(1)                                                NOT NULL DEFAULT 1,
  MAIL_USERNAME           VARCHAR(255)                                              NOT NULL DEFAULT '',
  MAIL_PASSWORD           VARBINARY(@AESCTR_CREDS_ENCODED_MAX_LEN) COLLATE 'binary' NOT NULL,
  MAIL_ASCII_ATTACHMENTS  TINYINT(1)                                                NOT NULL DEFAULT 0,
  MAIL_DEFAULT_SENDER     VARCHAR(255)                                              NOT NULL DEFAULT 'DoNotReply@smtp.gmail.com',
  MAIL_DEFAULT_SUBJECT    VARCHAR(255)                                              NOT NULL DEFAULT 'dSIPRouter System Notification',
  DSIP_CORE_LICENSE       VARBINARY(@AESCTR_CREDS_ENCODED_MAX_LEN) COLLATE 'binary' NOT NULL,
  DSIP_STIRSHAKEN_LICENSE VARBINARY(@AESCTR_CREDS_ENCODED_MAX_LEN) COLLATE 'binary' NOT NULL,
  DSIP_TRANSNEXUS_LICENSE VARBINARY(@AESCTR_CREDS_ENCODED_MAX_LEN) COLLATE 'binary' NOT NULL,
  DSIP_MSTEAMS_LICENSE    VARBINARY(@AESCTR_CREDS_ENCODED_MAX_LEN) COLLATE 'binary' NOT NULL,
  CHECK (`ROLE` IN ('', 'outbound', 'inout')),
  PRIMARY KEY (DSIP_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  MIN_ROWS = 1;
/*!40101 SET character_set_client = @saved_cs_client */;

-- Update dsip_settings table for current dsiprouter instance, then
-- Sync changes to dsip_settings across same cluster with the following exceptions:
-- DSIP_ID is unchanged, it is associated to a single node
-- DSIP_CLUSTER_ID is unchanged
-- DSIP_CLUSTER_SYNC is unchanged
-- HOMER_ID is unchanged, it is associated to a single node
-- NETWORK_MODE is unchanged
-- IPV6_ENABLED is unchanged
-- INTERNAL_IP_ADDR is unchanged
-- INTERNAL_IP_NET is unchanged
-- INTERNAL_IP6_ADDR is unchanged
-- INTERNAL_IP6_NET is unchanged
-- INTERNAL_FQDN is unchanged
-- EXTERNAL_IP_ADDR is unchanged
-- EXTERNAL_IP6_ADDR is unchanged
-- EXTERNAL_FQDN is unchanged
-- PUBLIC_IFACE is unchanged
-- PRIVATE_IFACE is unchanged
-- DSIP_CORE_LICENSE is unchanged, it is associated to a single node
-- DSIP_STIRSHAKEN_LICENSE is unchanged, it is associated to a single node
-- DSIP_MSTEAMS_LICENSE is unchanged, it is associated to a single node
-- DSIP_TRANSNEXUS_LICENSE is unchanged, it is associated to a single node
DROP PROCEDURE IF EXISTS update_dsip_settings;
DELIMITER //
CREATE PROCEDURE update_dsip_settings(
  IN NEW_DSIP_ID VARBINARY(@HASHED_CREDS_ENCODED_MAX_LEN),
  IN NEW_DSIP_CLUSTER_ID INT UNSIGNED,
  IN NEW_DSIP_CLUSTER_SYNC TINYINT(1),
  IN NEW_DSIP_PROTO VARCHAR(16),
  IN NEW_DSIP_PORT INT,
  IN NEW_DSIP_USERNAME VARCHAR(255),
  IN NEW_DSIP_PASSWORD VARBINARY(@HASHED_CREDS_ENCODED_MAX_LEN),
  IN NEW_DSIP_IPC_PASS VARBINARY(@AESCTR_CREDS_ENCODED_MAX_LEN),
  IN NEW_DSIP_API_PROTO VARCHAR(16),
  IN NEW_DSIP_API_PORT INT,
  IN NEW_DSIP_PRIV_KEY VARCHAR(255),
  IN NEW_DSIP_PID_FILE VARCHAR(255),
  IN NEW_DSIP_UNIX_SOCK VARCHAR(255),
  IN NEW_DSIP_IPC_SOCK VARCHAR(255),
  IN NEW_DSIP_API_TOKEN VARBINARY(@AESCTR_CREDS_ENCODED_MAX_LEN),
  IN NEW_DSIP_LOG_LEVEL INT,
  IN NEW_DSIP_LOG_FACILITY INT,
  IN NEW_DSIP_SSL_KEY VARCHAR(255),
  IN NEW_DSIP_SSL_CERT VARCHAR(255),
  IN NEW_DSIP_SSL_CA VARCHAR(255),
  IN NEW_DSIP_SSL_EMAIL VARCHAR(255),
  IN NEW_DSIP_CERTS_DIR VARCHAR(255),
  IN NEW_VERSION VARCHAR(32),
  IN NEW_DEBUG TINYINT(1),
  IN NEW_ROLE VARCHAR(32),
  IN NEW_GUI_INACTIVE_TIMEOUT INT UNSIGNED,
  IN NEW_KAM_DB_HOST VARCHAR(255),
  IN NEW_KAM_DB_DRIVER VARCHAR(255),
  IN NEW_KAM_DB_TYPE VARCHAR(255),
  IN NEW_KAM_DB_PORT VARCHAR(255),
  IN NEW_KAM_DB_NAME VARCHAR(255),
  IN NEW_KAM_DB_USER VARCHAR(255),
  IN NEW_KAM_DB_PASS VARBINARY(@AESCTR_CREDS_ENCODED_MAX_LEN),
  IN NEW_KAM_KAMCMD_PATH VARCHAR(255),
  IN NEW_KAM_CFG_PATH VARCHAR(255),
  IN NEW_KAM_TLSCFG_PATH VARCHAR(255),
  IN NEW_RTP_CFG_PATH VARCHAR(255),
  IN NEW_FLT_CARRIER INT,
  IN NEW_FLT_PBX INT,
  IN NEW_FLT_MSTEAMS INT,
  IN NEW_FLT_OUTBOUND INT,
  IN NEW_FLT_INBOUND INT,
  IN NEW_FLT_LCR_MIN INT,
  IN NEW_FLT_FWD_MIN INT,
  IN NEW_DEFAULT_AUTH_DOMAIN VARCHAR(255),
  IN NEW_TELEBLOCK_GW_ENABLED TINYINT(1),
  IN NEW_TELEBLOCK_GW_IP VARCHAR(255),
  IN NEW_TELEBLOCK_GW_PORT VARCHAR(255),
  IN NEW_TELEBLOCK_MEDIA_IP VARCHAR(255),
  IN NEW_TELEBLOCK_MEDIA_PORT VARCHAR(255),
  IN NEW_FLOWROUTE_ACCESS_KEY VARCHAR(255),
  IN NEW_FLOWROUTE_SECRET_KEY VARCHAR(255),
  IN NEW_FLOWROUTE_API_ROOT_URL VARCHAR(255),
  IN NEW_HOMER_ID BIGINT,
  IN NEW_HOMER_HEP_HOST VARCHAR(255),
  IN NEW_HOMER_HEP_PORT INT,
  IN NEW_NETWORK_MODE INT,
  IN NEW_IPV6_ENABLED TINYINT(1),
  IN NEW_INTERNAL_IP_ADDR VARCHAR(255),
  IN NEW_INTERNAL_IP_NET VARCHAR(255),
  IN NEW_INTERNAL_IP6_ADDR VARCHAR(255),
  IN NEW_INTERNAL_IP6_NET VARCHAR(255),
  IN NEW_INTERNAL_FQDN VARCHAR(255),
  IN NEW_EXTERNAL_IP_ADDR VARCHAR(255),
  IN NEW_EXTERNAL_IP6_ADDR VARCHAR(255),
  IN NEW_EXTERNAL_FQDN VARCHAR(255),
  IN NEW_PUBLIC_IFACE VARCHAR(255),
  IN NEW_PRIVATE_IFACE VARCHAR(255),
  IN NEW_UPLOAD_FOLDER VARCHAR(255),
  IN NEW_MAIL_SERVER VARCHAR(255),
  IN NEW_MAIL_PORT INT,
  IN NEW_MAIL_USE_TLS TINYINT(1),
  IN NEW_MAIL_USERNAME VARCHAR(255),
  IN NEW_MAIL_PASSWORD VARBINARY(@AESCTR_CREDS_ENCODED_MAX_LEN),
  IN NEW_MAIL_ASCII_ATTACHMENTS TINYINT(1),
  IN NEW_MAIL_DEFAULT_SENDER VARCHAR(255),
  IN NEW_MAIL_DEFAULT_SUBJECT VARCHAR(255),
  IN NEW_DSIP_CORE_LICENSE VARBINARY(@AESCTR_CREDS_ENCODED_MAX_LEN),
  IN NEW_DSIP_STIRSHAKEN_LICENSE VARBINARY(@AESCTR_CREDS_ENCODED_MAX_LEN),
  IN NEW_DSIP_TRANSNEXUS_LICENSE VARBINARY(@AESCTR_CREDS_ENCODED_MAX_LEN),
  IN NEW_DSIP_MSTEAMS_LICENSE VARBINARY(@AESCTR_CREDS_ENCODED_MAX_LEN)
)
BEGIN
  START TRANSACTION;

  REPLACE INTO dsip_settings
  VALUES (NEW_DSIP_ID,
          NEW_DSIP_CLUSTER_ID,
          NEW_DSIP_CLUSTER_SYNC,
          NEW_DSIP_PROTO,
          NEW_DSIP_PORT,
          NEW_DSIP_USERNAME,
          NEW_DSIP_PASSWORD,
          NEW_DSIP_IPC_PASS,
          NEW_DSIP_API_PROTO,
          NEW_DSIP_API_PORT,
          NEW_DSIP_PRIV_KEY,
          NEW_DSIP_PID_FILE,
          NEW_DSIP_UNIX_SOCK,
          NEW_DSIP_IPC_SOCK,
          NEW_DSIP_API_TOKEN,
          NEW_DSIP_LOG_LEVEL,
          NEW_DSIP_LOG_FACILITY,
          NEW_DSIP_SSL_KEY,
          NEW_DSIP_SSL_CERT,
          NEW_DSIP_SSL_CA,
          NEW_DSIP_SSL_EMAIL,
          NEW_DSIP_CERTS_DIR,
          NEW_VERSION,
          NEW_DEBUG,
          NEW_ROLE,
          NEW_GUI_INACTIVE_TIMEOUT,
          NEW_KAM_DB_HOST,
          NEW_KAM_DB_DRIVER,
          NEW_KAM_DB_TYPE,
          NEW_KAM_DB_PORT,
          NEW_KAM_DB_NAME,
          NEW_KAM_DB_USER,
          NEW_KAM_DB_PASS,
          NEW_KAM_KAMCMD_PATH,
          NEW_KAM_CFG_PATH,
          NEW_KAM_TLSCFG_PATH,
          NEW_RTP_CFG_PATH,
          NEW_FLT_CARRIER,
          NEW_FLT_PBX,
          NEW_FLT_MSTEAMS,
          NEW_FLT_OUTBOUND,
          NEW_FLT_INBOUND,
          NEW_FLT_LCR_MIN,
          NEW_FLT_FWD_MIN,
          NEW_DEFAULT_AUTH_DOMAIN,
          NEW_TELEBLOCK_GW_ENABLED,
          NEW_TELEBLOCK_GW_IP,
          NEW_TELEBLOCK_GW_PORT,
          NEW_TELEBLOCK_MEDIA_IP,
          NEW_TELEBLOCK_MEDIA_PORT,
          NEW_FLOWROUTE_ACCESS_KEY,
          NEW_FLOWROUTE_SECRET_KEY,
          NEW_FLOWROUTE_API_ROOT_URL,
          NEW_HOMER_ID,
          NEW_HOMER_HEP_HOST,
          NEW_HOMER_HEP_PORT,
          NEW_NETWORK_MODE,
          NEW_IPV6_ENABLED,
          NEW_INTERNAL_IP_ADDR,
          NEW_INTERNAL_IP_NET,
          NEW_INTERNAL_IP6_ADDR,
          NEW_INTERNAL_IP6_NET,
          NEW_INTERNAL_FQDN,
          NEW_EXTERNAL_IP_ADDR,
          NEW_EXTERNAL_IP6_ADDR,
          NEW_EXTERNAL_FQDN,
          NEW_PUBLIC_IFACE,
          NEW_PRIVATE_IFACE,
          NEW_UPLOAD_FOLDER,
          NEW_MAIL_SERVER,
          NEW_MAIL_PORT,
          NEW_MAIL_USE_TLS,
          NEW_MAIL_USERNAME,
          NEW_MAIL_PASSWORD,
          NEW_MAIL_ASCII_ATTACHMENTS,
          NEW_MAIL_DEFAULT_SENDER,
          NEW_MAIL_DEFAULT_SUBJECT,
          NEW_DSIP_CORE_LICENSE,
          NEW_DSIP_STIRSHAKEN_LICENSE,
          NEW_DSIP_TRANSNEXUS_LICENSE,
          NEW_DSIP_MSTEAMS_LICENSE);

  IF NEW_DSIP_CLUSTER_SYNC = 1 THEN
    UPDATE dsip_settings
    SET DSIP_PROTO             = NEW_DSIP_PROTO,
        DSIP_PORT              = NEW_DSIP_PORT,
        DSIP_USERNAME          = NEW_DSIP_USERNAME,
        DSIP_PASSWORD          = NEW_DSIP_PASSWORD,
        DSIP_IPC_PASS          = NEW_DSIP_IPC_PASS,
        DSIP_API_PROTO         = NEW_DSIP_API_PROTO,
        DSIP_API_PORT          = NEW_DSIP_API_PORT,
        DSIP_PRIV_KEY          = NEW_DSIP_PRIV_KEY,
        DSIP_PID_FILE          = NEW_DSIP_PID_FILE,
        DSIP_UNIX_SOCK         = NEW_DSIP_UNIX_SOCK,
        DSIP_IPC_SOCK          = NEW_DSIP_IPC_SOCK,
        DSIP_API_TOKEN         = NEW_DSIP_API_TOKEN,
        DSIP_LOG_LEVEL         = NEW_DSIP_LOG_LEVEL,
        DSIP_LOG_FACILITY      = NEW_DSIP_LOG_FACILITY,
        DSIP_SSL_KEY           = NEW_DSIP_SSL_KEY,
        DSIP_SSL_CERT          = NEW_DSIP_SSL_CERT,
        DSIP_SSL_CA            = NEW_DSIP_SSL_CA,
        DSIP_SSL_EMAIL         = NEW_DSIP_SSL_EMAIL,
        DSIP_CERTS_DIR         = NEW_DSIP_CERTS_DIR,
        VERSION                = NEW_VERSION,
        DEBUG                  = NEW_DEBUG,
        `ROLE`                 = NEW_ROLE,
        GUI_INACTIVE_TIMEOUT   = NEW_GUI_INACTIVE_TIMEOUT,
        KAM_DB_HOST            = NEW_KAM_DB_HOST,
        KAM_DB_DRIVER          = NEW_KAM_DB_DRIVER,
        KAM_DB_TYPE            = NEW_KAM_DB_TYPE,
        KAM_DB_PORT            = NEW_KAM_DB_PORT,
        KAM_DB_NAME            = NEW_KAM_DB_NAME,
        KAM_DB_USER            = NEW_KAM_DB_USER,
        KAM_DB_PASS            = NEW_KAM_DB_PASS,
        KAM_KAMCMD_PATH        = NEW_KAM_KAMCMD_PATH,
        KAM_CFG_PATH           = NEW_KAM_CFG_PATH,
        KAM_TLSCFG_PATH        = NEW_KAM_TLSCFG_PATH,
        RTP_CFG_PATH           = NEW_RTP_CFG_PATH,
        FLT_CARRIER            = NEW_FLT_CARRIER,
        FLT_PBX                = NEW_FLT_PBX,
        FLT_MSTEAMS            = NEW_FLT_MSTEAMS,
        FLT_OUTBOUND           = NEW_FLT_OUTBOUND,
        FLT_INBOUND            = NEW_FLT_INBOUND,
        FLT_LCR_MIN            = NEW_FLT_LCR_MIN,
        FLT_FWD_MIN            = NEW_FLT_FWD_MIN,
        DEFAULT_AUTH_DOMAIN    = NEW_DEFAULT_AUTH_DOMAIN,
        TELEBLOCK_GW_ENABLED   = NEW_TELEBLOCK_GW_ENABLED,
        TELEBLOCK_GW_IP        = NEW_TELEBLOCK_GW_IP,
        TELEBLOCK_GW_PORT      = NEW_TELEBLOCK_GW_PORT,
        TELEBLOCK_MEDIA_IP     = NEW_TELEBLOCK_MEDIA_IP,
        TELEBLOCK_MEDIA_PORT   = NEW_TELEBLOCK_MEDIA_PORT,
        FLOWROUTE_ACCESS_KEY   = NEW_FLOWROUTE_ACCESS_KEY,
        FLOWROUTE_SECRET_KEY   = NEW_FLOWROUTE_SECRET_KEY,
        FLOWROUTE_API_ROOT_URL = NEW_FLOWROUTE_API_ROOT_URL,
        HOMER_HEP_HOST         = NEW_HOMER_HEP_HOST,
        HOMER_HEP_PORT         = NEW_HOMER_HEP_PORT,
        UPLOAD_FOLDER          = NEW_UPLOAD_FOLDER,
        MAIL_SERVER            = NEW_MAIL_SERVER,
        MAIL_PORT              = NEW_MAIL_PORT,
        MAIL_USE_TLS           = NEW_MAIL_USE_TLS,
        MAIL_USERNAME          = NEW_MAIL_USERNAME,
        MAIL_PASSWORD          = NEW_MAIL_PASSWORD,
        MAIL_ASCII_ATTACHMENTS = NEW_MAIL_ASCII_ATTACHMENTS,
        MAIL_DEFAULT_SENDER    = NEW_MAIL_DEFAULT_SENDER,
        MAIL_DEFAULT_SUBJECT   = NEW_MAIL_DEFAULT_SUBJECT
    WHERE DSIP_CLUSTER_ID = NEW_DSIP_CLUSTER_ID
      AND DSIP_CLUSTER_SYNC = 1
      AND DSIP_ID != NEW_DSIP_ID;
  END IF;
  COMMIT;
END //
DELIMITER ;
